version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    # Check for updates once daily
    schedule:
      interval: "daily"